############# check api #############
tvi_monitor.routing.api.check(s):
  path: /check
  methods: [GET]
  defaults:
    _controller: tvi_monitor.controller.api:checksAction

tvi_monitor.routing.api.check:
  path: /check/{id}
  methods: [GET]
  defaults:
    _controller: tvi_monitor.controller.api:checkAction
    id:
    requirements:
      id: '[\w:]+'

tvi_monitor.routing.api.check_status(s):
  path: /status
  methods: [GET]
  defaults:
    _controller: tvi_monitor.controller.api:checkStatusesAction

tvi_monitor.routing.api.check_status:
  path: /status/{id}
  methods: [GET]
  defaults:
    _controller: tvi_monitor.controller.api:checkStatusAction
    id:
    requirements:
      id: '[\w:]+'

############# info api #############

tvi_monitor.routing.api.info.check(s):
  path: /info/check
  methods: [GET]
  defaults:
    _controller: tvi_monitor.controller.api:checkInfosAction

tvi_monitor.routing.api.info.check:
  path: /info/check/{id}
  methods: [GET]
  defaults:
    _controller: tvi_monitor.controller.api:checkInfoAction
    id:
    requirements:
      id: '[\w:]+'

tvi_monitor.routing.api.info.group(s):
  path: /info/group
  methods: [GET]
  defaults:
    _controller: tvi_monitor.controller.api:groupInfosAction

tvi_monitor.routing.api.info.group:
  path: /info/group/{id}
  methods: [GET]
  defaults:
    _controller: tvi_monitor.controller.api:groupInfoAction
    id:
    requirements:
      id: '[\w:]+'

tvi_monitor.routing.api.info.tag(s):
  path: /info/tag
  methods: [GET]
  defaults:
    _controller: tvi_monitor.controller.api:tagInfosAction

tvi_monitor.routing.api.info.tag:
  path: /info/tag/{id}
  methods: [GET]
  defaults:
    _controller: tvi_monitor.controller.api:tagInfoAction
    id:
    requirements:
      id: '[\w:]+'
