tvi_monitor.routing.api.check:
  path: /check/{check}
  methods: [GET]
  defaults:
    _controller: tvi_monitor.controller.api:checkAction
    check:
    requirements:
        check: '[\w:]+'

tvi_monitor.routing.api.check(s):
  path: /checks
  methods: [GET]
  defaults:
    _controller: tvi_monitor.controller.api:checkListAction

tvi_monitor.routing.api.checks_status:
  path: /status/{checkSingle}
  methods: [GET]
  defaults:
    _controller: tvi_monitor.controller.api:checkStatusAction
    checkSingle:
    requirements:
      checkSingle: '[\w:]+'

tvi_monitor.routing.api.info.check(s):
    path: /info/checks
    methods: [GET]
    defaults:
      _controller: tvi_monitor.controller.api:checkListInfoAction

#tvi_monitor.routing.api.info.states:
#    path: /info/statuses
#    methods: [GET]
#    defaults:
#        _controller: tvi_monitor.controller.api:statusListAction
#
#tvi_monitor.routing.api.info.groups:
#    path: /info/groups
#    methods: [GET]
#    defaults:
#        _controller: tvi_monitor.controller.api:groupListAction
#
#tvi_monitor.routing.api.info.checks:
#    path: /info/check/{group}
#    methods: [GET]
#    defaults:
#        _controller: tvi_monitor.controller.api:checkListAction
#        group:
#    requirements:
#        group: '[\w\.-]+'
#
#tvi_monitor.routing.api.status:
#    path: /status/{group}/{check}
#    methods: [GET]
#    defaults:
#        _controller: tvi_monitor.controller.api:statusAction
#        check:
#        group:
#    requirements:
#        group: '[\w\.-]+'
#        check: '[\w\.@-]+'
#
#tvi_monitor.routing.api.check:
#    path: /check/{group}/{check}
#    methods: [GET]
#    defaults:
#        _controller: tvi_monitor.controller.api:checkAction
#        group:
#        check:
#    requirements:
#        group: '[\w\.-]+'
#        check: '[\w\.@-]+'
