tvi_monitor.routing.api.check:
  path: /check/{check}
  methods: [GET]
  defaults:
    _controller: tvi_monitor.controller.api:checkAction
    check:
    requirements:
        check: '[\w:]+'

tvi_monitor.routing.api.check(s):
  path: /checks
  methods: [GET]
  defaults:
    _controller: tvi_monitor.controller.api:checkListAction

tvi_monitor.routing.api.checks_status:
  path: /status/{checkSingle}
  methods: [GET]
  defaults:
    _controller: tvi_monitor.controller.api:checkStatusAction
    checkSingle:
    requirements:
      checkSingle: '[\w:]+'

tvi_monitor.routing.api.info.check(s):
    path: /info/checks
    methods: [GET]
    defaults:
      _controller: tvi_monitor.controller.api:checkInfoListAction

tvi_monitor.routing.api.info.group(s):
  path: /info/groups
  methods: [GET]
  defaults:
    _controller: tvi_monitor.controller.api:groupInfoListAction

tvi_monitor.routing.api.info.tag(s):
  path: /info/tags
  methods: [GET]
  defaults:
    _controller: tvi_monitor.controller.api:tagInfoListAction

