<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.monitor.command.list_checks' shared service.

return $this->services['console.command.public_alias.monitor.command.list_checks'] = new \Tvi\MonitorBundle\Command\CheckInfoCommand(($this->services['monitor.runner_manager'] ?? $this->services['monitor.runner_manager'] = new \Tvi\MonitorBundle\Runner\RunnerManager($this)));
