<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'monitor.runner_manager' shared service.

return $this->services['monitor.runner_manager'] = new \Tvi\MonitorBundle\Runner\RunnerManager($this);
