build:
  environment:
    php:
      version: 7.2
  nodes:
    analysis:
      project_setup:
        override:
          - true
      tests:
        override:
          - php-scrutinizer-run
          - command: phpcs-run
    tests: true
    coverage:
      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clove ./build/coverage/clover.xml
            coverage:
              file: ./build/coverage/clover.xml
              format: clover

before_commands:
      - composer global require hirak/prestissimo

filter:
  paths:
    - src/*
  excluded_paths:
    - tests/
    - vendor/

checks:
  php: true

coding_style:
  php: {}

imports:
  - php

tools:
  external_code_coverage: true

    excluded_dirs:
      - vendor

  php_mess_detector:
    enabled: true

  php_changetracking: true

  php_analyzer:
    config:
      loops_must_use_braces: true

  php_code_sniffer:
    config:
      standard: PSR4

  php_cpd:
    enabled: true

  php_loc:
    enabled: true
    excluded_dirs:
      - vendor

  php_cs_fixer:
    enabled: true
    config:
      level: all

  sensiolabs_security_checker: true
