language: php

php:
  - 7.1
  - 7.2
  - nightly
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION=4.1.*

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: SYMFONY_VERSION=4.1.*
    - php: 7.2
      env: SYMFONY_VERSION=2.8.*
  allow_failures:
    - php: nightly
    - php: hhvm

before_install:
  - echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SYMFONY_VERSION; fi
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || phpenv config-rm xdebug.ini'

install:
  - composer update --prefer-source $COMPOSER_FLAGS

script:
  - ./vendor/bin/phpunit --coverage-text
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || ./vendor/bin/phpunit'
