language: php
sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  apt:
    packages:
      - parallel

php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm

env:
  - SYMFONY_VERSION=4.1.*

matrix:

  include:
    - php: 7.1
      env: SYMFONY_VERSION=2.8.*
    - php: 7.2
      env: SYMFONY_VERSION=2.8.*
    - php: hhvm
      env: SYMFONY_VERSION=2.8.*
  fast_finish: true
  allow_failures:
    - php: hhvm

before_install:
  # disable xdebug if available
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  # disable default memory limit
  - export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo memory_limit = -1 >> $INI
  # install faseter composer plugin
  - composer global require hirak/prestissimo
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SYMFONY_VERSION; fi

install:
  - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
  - composer install $flags

script:
  - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then ./vendor/bin/phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./vendor/bin/phpunit --coverage-text; fi

