language: php

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2
  - hhvm

env:
  - SYMFONY_VERSION=4.1.*

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION=2.8.*
    - php: 7.2
      env: SYMFONY_VERSION=2.8.*
    - php: hhvm
      env: SYMFONY_VERSION=2.8.*
  fast_finish: true
  allow_failures:
    - php: hhvm

before_install:
  # disable default memory limit
  - export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo memory_limit = -1 >> $INI
  # install faseter composer plugin
  - composer global require hirak/prestissimo
  - composer self-update

install:
  - if [[ $SYMFONY_VERSION != "" ]]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update -n; fi
  - composer update $COMPOSER_FLAGS --prefer-dist --no-interaction

script:
  - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then ./vendor/bin/phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./vendor/bin/phpunit --coverage-text; fi

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  on_success: never
  on_failure: always
