language: Php

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2
  - hhvm
  - nightly

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.1.*
  - SYMFONY_VERSION=4.1.*

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

before_install:
  # disable default memory limit
  - export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo memory_limit = -1 >> $INI
  # install faseter composer plugin
  - composer global require hirak/prestissimo
  - composer self-update

install:
  - if [[ $SYMFONY_VERSION != "" ]]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update -n; fi
  - composer update --no-interaction $COMPOSER_FLAGS

script:
  - ./vendor/bin/phpunit

notifications:
  on_success: never
  on_failure: always
