language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION=4.1.*

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: SYMFONY_VERSION=2.8.*
    - php: 7.1
      env: SYMFONY_VERSION=2.8.*
    - php: 7.2
      env: SYMFONY_VERSION=2.8.*
    - php: 7.3
      env: SYMFONY_VERSION=2.8.*
  allow_failures:
    - php: hhvm

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SYMFONY_VERSION; fi

install:
  - composer update --prefer-source $COMPOSER_FLAGS

script:
  - ./vendor/bin/phpunit --coverage-text

