tvi_monitor:
  checks:
    guzzle_http_service:
      check:
        requestOrUrl: "google.com"
        #headers: []
        #options: []
        #statusCode: 200
        #method: 'GET'
        #content: null
        #body: null
    guzzle_http_service(s):
      items:
        a:
          check:
            requestOrUrl: "google.com"
        b:
          check:
            requestOrUrl: "google.com"
