tvi_monitor:
  checks:
    core:guzzle_http_service:
      # group: "group"
      # tags: ["tag"]
      check:
        requestOrUrl: "http://google.com"
        # headers: []
        # options: []
        # statusCode: 200
        # method: 'GET'
        # content: null
        # body: null
    core:guzzle_http_service(s):
      items:
        a:
          check:
            requestOrUrl: "http://google.com"
        b:
          check:
            requestOrUrl: "http://ya.ru"
