tvi_monitor:
  checks:
    yaml_file:
      # group: "group"
      # tags: ["tag"]
      check:
        files: ["/tmp/test.yml"]
    yaml_file(s):
      items:
        a:
          check:
            files: "/tmp/test.yml"
        b:
          check:
            files: ["/tmp/test.yml"]
