tvi_monitor:
  checks:
    core:ini_file:
      # group: "group"
      # tags: ["tag"]
      check:
        files: ["/tmp/test.ini"]
    core:ini_file(s):
      items:
        a:
          check:
            files: "/tmp/test.ini"
        b:
          check:
            files: ["/tmp/test.ini"]
