<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHX6u2ZS\app4DebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHX6u2ZS/app4DebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHX6u2ZS.legacy');

    return;
}

if (!\class_exists(app4DebugProjectContainer::class, false)) {
    \class_alias(\ContainerHX6u2ZS\app4DebugProjectContainer::class, app4DebugProjectContainer::class, false);
}

return new \ContainerHX6u2ZS\app4DebugProjectContainer(array(
    'container.build_hash' => 'HX6u2ZS',
    'container.build_id' => '51d72794',
    'container.build_time' => 1536746941,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHX6u2ZS');
