tvi_monitor:
  checks:
    json_file:
      # group: "group"
      # tags: ["tag"]
      check:
        files: ["/tmp/test.json"]
    json_file(s):
      items:
        a:
          check:
            files: "/tmp/test.json"
        b:
          check:
            files: ["/tmp/test.json"]
