tvi_monitor:
  checks:
    core:cpu_performance:
      # group: "group"
      # tags: ["tag"]
      check:
        # minPerformance: 0.5
    core:cpu_performance(s):
      items:
        a:
          check:
            minPerformance: 0.6
        b:
          check:
