tvi_monitor:
  checks:
    cpu_performance:
      check:
        # minPerformance: 0.5
    cpu_performance(s):
      items:
        a:
          check:
            minPerformance: 0.6
        b:
          check:
