checks:
  tvi_php_version:
    check:
      expectedVersion: "7.0"
      operator: ">="
  tvi_php_version(s):
    items:
      a:
        check:
          expectedVersion: "7.0"
          operator: ">="
      b:
        check:
          expectedVersion: "7.0"

