tvi_monitor:
  checks:
    php_version:
      check:
        expectedVersion: "7.0"
        operator: ">="
    php_version(s):
      items:
        a:
          check:
            expectedVersion: "7.0"
        b:
          check:
            expectedVersion: "7.0"
            operator: ">="
