tvi_monitor:
  checks:
    core:http_service:
      # group: "group"
      # tags: ["tag"]
      check:
        host: "google.com"
        # port: 80
        # path: "/"
        # statusCode: ~
        # content: null
    core:http_service(s):
      items:
        a:
          check:
            host: "google.com"
        b:
          check:
            host: "ya.ru"
