tvi_monitor:
  checks:
    http_service:
      check:
        host: "google.com"
        #port: 80
        #path: "/"
        #statusCode: ~
        #content: null
    http_service(s):
      items:
        a:
          check:
            host: "google.com"
        b:
          check:
            host: "ya.ru"
