tvi_monitor:
  checks:
    core:rabbit_mq:queue_consumer:
      # group: "group"
      # tags: ["tag"]
      check:
        # host: 'localhost'
        # port: 5672
        # user: 'guest'
        # password: 'guest'
        # vhost: '/'
    core:rabbit_mq:queue_consumer(s):
      items:
        a:
          check:
            dsn: "amqp://guest:pass@localhost:5672/"
        b:
          check:
