parameters:

  monitor.command.check.info.class: Tvi\MonitorBundle\Command\CheckInfoCommand
  monitor.command.check.health.class: Tvi\MonitorBundle\Command\CheckHealthCommand

services:

  tvi_monitor.command.check.info:
    public: true
    class: "%monitor.command.check.info.class%"
    arguments:
      - "@tvi_monitor.runner.manager"
    tags:
      - {name: console.command, command: "tvi:monitor:check:info"}

  tvi_monitor.command.check.health:
    public: true
    class: "%monitor.command.check.health.class%"
    arguments:
      - "@tvi_monitor.reporters.manager"
      - "@tvi_monitor.runner.manager"
    tags:
      - {name: console.command, command: "tvi:monitor:check:health"}

