parameters:

  tvi_monitor.checks.registry.class: Tvi\MonitorBundle\Check\Registry
  tvi_monitor.runner.class: Tvi\MonitorBundle\Runner\Runner
  tvi_monitor.reporter.raw_console.class: Tvi\MonitorBundle\Runner\Reporter\RawConsoleReporter
  tvi_monitor.reporter.console.class: Tvi\MonitorBundle\Runner\Reporter\ConsoleReporter

services:
  tvi_monitor.checks.registry:
    public: true
    class: "%tvi_monitor.checks.registry.class%"
    calls:
      - method: setContainer
        arguments:
          - "@service_container"

#  monitor.runner:
#    public: true
#    class: "%monitor.runner.class%"

#  monitor.reporter.raw_console:
#    class: "%monitor.reporter.raw_console.class%"
#
#  monitor.reporter.console:
#    class: "%monitor.reporter.console.class%"
