parameters:

  tvi_monitor.checks.registry.class: Tvi\MonitorBundle\Check\Registry
  tvi_monitor.runner.manager.class: Tvi\ MonitorBundle\Runner\RunnerManager

services:
  tvi_monitor.checks.registry:
    public: true
    class: "%tvi_monitor.checks.registry.class%"
    calls:
      - method: setContainer
        arguments:
          - "@service_container"

  tvi_monitor.runner.manager:
    public: true
    class: "%tvi_monitor.runner.manager.class%"
    arguments:
      - "@tvi_monitor.checks.registry"

