parameters:
  tvi_monitor.checks.manager.class: Tvi\MonitorBundle\Check\CheckManager
  tvi_monitor.runner.manager.class: Tvi\MonitorBundle\Runner\RunnerManager
  tvi_monitor.checks.plugin_finder.class: Tvi\MonitorBundle\Check\CheckPluginFinder
  tvi_monitor.checks.plugin_finder_path.class: Tvi\MonitorBundle\Check\CheckPluginFinderPath

services:
  tvi_monitor.checks.plugin_search_path:
    public: true
    class: "%tvi_monitor.checks.plugin_finder_path.class%"
    arguments:
      - "@=parameter('kernel.bundles_metadata')['TviMonitorBundle']['path']"
      - ['Check/**']

    tags:
      - {name: tvi_monitor.plugin_search_path}

  tvi_monitor.checks.plugin_finder:
    public: true
    class: "%tvi_monitor.checks.plugin_finder.class%"

  tvi_monitor.checks.manager:
    public: true
    class: "%tvi_monitor.checks.manager.class%"
    calls:
      - method: setContainer
        arguments:
          - "@service_container"

  tvi_monitor.runner.manager:
    public: true
    class: "%tvi_monitor.runner.manager.class%"
    arguments:
      - "@tvi_monitor.checks.manager"


