parameters:

  tvi_monitor.checks.registry.class: Tvi\MonitorBundle\Check\Registry

services:
  tvi_monitor.checks.registry:
    public: true
    class: "%tvi_monitor.checks.registry.class%"
    calls:
      - method: setContainer
        arguments:
          - "@service_container"

