parameters:
  tvi_monitor.checks.manager.class: Tvi\MonitorBundle\Check\Manager
  tvi_monitor.runner.manager.class: Tvi\MonitorBundle\Runner\Manager

services:
  tvi_monitor.checks.manager:
    public: true
    class: "%tvi_monitor.checks.manager.class%"
    calls:
      - method: setContainer
        arguments:
          - "@service_container"

  tvi_monitor.runner.manager:
    public: true
    class: "%tvi_monitor.runner.manager.class%"
    arguments:
      - "@tvi_monitor.checks.manager"

