parameters:
  tvi_monitor.reporter.swift_mailer.class: Tvi\MonitorBundle\Reporter\SwiftMailerReporter

services:
  tvi_monitor.reporter.swift_mailer:
    public: true
    class: "%tvi_monitor.reporter.swift_mailer.class%"
    arguments:
      - "@mailer"
      - "%tvi_monitor.mailer.recipient%"
      - "%tvi_monitor.mailer.sender%"
      - "%tvi_monitor.mailer.subject%"
      - "%tvi_monitor.mailer.send_on_warning%"
