tvi_monitor:
  checks:
    core:class_exists:
      # group: "group"
      # tags: ["tag"]
      check:
        classNames: ['\Tvi\MonitorBundle\Check\ClassExists\Check']
        # autoload: true
    core:class_exists(s):
      items:
        a:
          check:
            classNames: '\Tvi\MonitorBundle\Check\ClassExists\Check'
            autoload: false
        b:
          check:
            classNames: ['\Tvi\MonitorBundle\Check\ClassExists\Check']
