tvi_monitor:
  checks:
    core:extension_not_loaded:
      # group: "group"
      # tags: ["tag"]
      check:
        extensionName: ["xdebug"]
    core:extension_not_loaded(s):
      items:
        a:
          check:
            extensionName: ["test"]
        b:
          check:
            extensionName: "xdebug"
