tvi_monitor:
  checks:
    core:dir_writable:
      # group: "group"
      # tags: ["tag"]
      check:
        path: "/"
    core:dir_writable(s):
      items:
        a:
          check:
            path: "/"
        b:
          check:
            path: ["/", "/tmp"]
