tvi_monitor:
  checks:
    core:php_flag:
      # group: "group"
      # tags: ["tag"]
      check:
        settingName: ["session.use_only_cookies"]
        expectedValue: true
    core:php_flag(s):
      items:
        a:
          check:
            settingName: "session.use_only_cookies"
            expectedValue: true
        b:
          check:
            settingName: ["session.use_only_cookies"]
            expectedValue: true
