tvi_monitor:
  checks:
    core:disk_free:
      # group: "group"
      # tags: ["tag"]
      check:
        size: 10000
        # path:  "/"
    core:disk_free(s):
      items:
        a:
          check:
            size: 10000
        b:
          check:
            size: 10000
            path: "/tmp"
