tvi_monitor:
  checks:
    redis:
      # group: "group"
      # tags: ["tag"]
      check:
        # host: default 'localhost'
        # port: default 6379
        # auth:  default null
    redis(s):
      items:
        a:
          check:
        b:
          check:
