tvi_monitor:
  checks:
    rabbit_mq:
      # group: "group"
      # tags: ["tag"]
      check:
        # host: 'localhost'
        # port: 5672
        # user: 'guest'
        # password: 'guest'
        # vhost: '/'
    rabbit_mq(s):
      items:
        a:
          check:
        b:
          check:
