tvi_monitor:
  checks:
    core:process_running:
      # group: "group"
      # tags: ["tag"]
      check:
        processNameOrPid: "php"
    core:process_running(s):
      items:
        a:
          check:
            processNameOrPid: "nginx"
        b:
          check:
            processNameOrPid: 1
