tvi_monitor:
  checks:
    process_running:
      check:
        processNameOrPid: "Php"
    process_running(s):
      items:
        a:
          check:
            processNameOrPid: "nginx"
        b:
          check:
            processNameOrPid: 1
