tvi_monitor:
  checks:
    pdo_check:
      # group: "group"
      # tags: ["tag"]
      check:
        dsn: "mysql:host=localhost;dbname=testdb"
        username: "username"
        password: "password"
        # timeout: 1
    pdo_check(s):
      items:
        a:
          check:
            dsn: "mysql:host=localhost;dbname=testdb"
            username: "username"
            password: "password"
            timeout: 1
        b:
          check:
            dsn: "mysql:host=localhost;dbname=testdb"
            username: "username"
            password: "password"
            timeout: 1
