tvi_monitor:
  checks:
    core:security_advisory:
      # group: "group"
      # tags: ["tag"]
      # lable: "label"
      # descr: "descr"
      check:
      # lockFilePath: "%kernel.root_dir%/../composer.lock"
    core:security_advisory(s):
      # group: "group"
      # tags: ["tag"]
      # lable: "label"
      # descr: "descr"
      items:
        a:
          # group: "group"
          # tags: ["tag"]
          # lable: "label"
          # descr: "descr"
          check:
            lockFilePath: "%kernel.root_dir%/../composer.lock"
        b:
          check:
            lockFilePath: "../../../composer.lock"
