tvi_monitor:
  checks:
    security_advisory:
      # group: "group"
      # tags: ["tag"]
      check:
        lockFilePath: "../../../../composer.lock"
    security_advisory(s):
      items:
        a:
          check:
            lockFilePath: "../../../../composer.lock"
        b:
          check:
            lockFilePath: "../../../../composer.lock"
