tvi_monitor:
  checks:
    xml_file:
      check:
        files: '/tmp/test.xml'
    xml_file(s):
      items:
        a:
          check:
            files: '/tmp/test.xml'
        b:
          check:
            files: ['/tmp/test.xml']
