tvi_monitor:
  checks:
    core:xml_file:
      # group: "group"
      # tags: ["tag"]
      check:
        files: ["/tmp/test.xml"]
    core:xml_file(s):
      items:
        a:
          check:
            files: "/tmp/test.xml"
        b:
          check:
            files: ["/tmp/test.xml"]
