tvi_monitor:
  checks:
    php_extension:
      check:
        extensionName: ["apc"]
    php_extension(s):
      items:
        a:
          check:
            extensionName: ["apc"]
        b:
          check:
            extensionName: "apc"
