checks:
  tvi_php_extension:
    check:
      extensionName: ['apc']
  tvi_php_extension(s):
    items:
      a:
        check:
          extensionName: ['apc']
      b:
        check:
          extensionName: 'apc'
