tvi_monitor:
  checks:
    php_version:
      check:
        extensionName: ['apc']
    php_version(s):
      items:
        a:
          check:
            extensionName: ['apc']
        b:
          check:
            extensionName: 'apc'
