tvi_monitor:
  checks:
    core:extension_loaded:
      # group: "group"
      # tags: ["tag"]
      check:
        extensionName: ["apc"]
    core:extension_loaded(s):
      items:
        a:
          check:
            extensionName: ["apc"]
        b:
          check:
            extensionName: "apc"
