tvi_monitor:
  checks:
    core:apc_fragmentation:
      # group: "group"
      # tags: ["tag"]
      check:
        # warningThreshold: 70
        # criticalThreshold: 90
    core:apc_fragmentation(s):
      items:
        a:
          check:
            warningThreshold: 70
            criticalThreshold: 90
        b:
          check:
            warningThreshold: 70
            criticalThreshold: 90
