tvi_monitor:
  checks:
    disk_usage:
      check:
        #warningThreshold: 70
        #criticalThreshold: 80
        #path: "/"
    disk_usage(s):
      items:
        a:
          check:
            warningThreshold: 90
            criticalThreshold: 95
            path: "/tmp"
        b:
          check:
              warningThreshold: 60
              criticalThreshold: 95
              path: "/"
