tvi_monitor:
  checks:
    disk_usage:
      check:
        #warningThreshold:  default 70
        #criticalThreshold:  default 80
      #path: default /
    disk_usage(s):
      items:
        a:
          check:
            warningThreshold: 90 # default 70
            criticalThreshold: 95 # default 80
            path: /tmp
        b:
          check:
              warningThreshold: 60 # default 70
              criticalThreshold: 95 # default 80
              path: /
